remote_theme: pages-themes/cayman@v0.2.0

title: Ayesha Mehboob | Computer Science Student
description: Aspiring Software Developer | Interested in AI, Cybersecurity & Cloud Computing

# Custom Branding
primary-color: "#6C63FF"
secondary-color: "#4B45B2"
